version: '3.8'

services:
  db:
    image: postgres:13.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .db.env
    expose:
      - 5432
    restart: unless-stopped

  web:
    image: "${WEB_IMAGE}"
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
      - /var/run/bcraft:/var/run/gunicorn
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    image: "${NGINX_IMAGE}"
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
      - /var/run/bcraft:/var/run/bcraft
    ports:
      - "80:80"
    depends_on:
      - web
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume: