# Generated by Django 3.2.9 on 2021-11-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('views', models.IntegerField(null=True, verbose_name='views')),
                ('clicks', models.IntegerField(null=True, verbose_name='clicks')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='cost')),
            ],
            options={
                'verbose_name': 'statistics',
                'verbose_name_plural': 'statistics',
                'ordering': ('-date',),
            },
        ),
    ]
